services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-website
    ports:
      - "3222:3222"
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
